FROM python:3.12.7

# Set the working directory in the container
WORKDIR /app

# Copy the application code into the container
COPY . .

RUN pip install -r requirements.txt

# Expose the desired port (default is 8000)
EXPOSE 8000

# Run the application with Uvicorn
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
