FROM python:3.12.7

# Set the working directory in the container
WORKDIR /app

# Install the necessary PyTorch and related packages
RUN pip install torch==2.4.1 torchvision==0.19.1 torchaudio==2.4.1 --index-url https://download.pytorch.org/whl/cpu

# Install FastAPI and other dependencies
RUN pip install fastapi==0.115.2 python-multipart==0.0.12 uvicorn==0.32.0 transformers==4.46.2

# Copy the application code into the container
COPY . .

# Expose the desired port (default is 8000)
EXPOSE 8000

# Run the application with Uvicorn
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
